// GENERATED by scripts/gen-database-types.mjs from the applied migrations. Do not edit by hand.
// Regenerate: DATABASE_URL=... pnpm --filter @ironflow/api-client gen:types

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      activities: {
        Row: {
          id: string
          athlete_id: string
          sport: Database["public"]["Enums"]["sport"]
          sub_sport: string | null
          start_time: string
          local_tz_offset_min: number
          duration_s: number
          moving_time_s: number | null
          distance_m: number | null
          elevation_gain_m: number | null
          avg_hr: number | null
          max_hr: number | null
          avg_power_w: number | null
          normalized_power_w: number | null
          avg_speed_mps: number | null
          avg_gap_speed_mps: number | null
          avg_cadence: number | null
          swim_avg_pace_s_per_100m: number | null
          swim_stroke_count: number | null
          temperature_c: number | null
          humidity_pct: number | null
          avg_altitude_m: number | null
          external_load: number | null
          internal_load: number | null
          perceived_load: number | null
          rpe: number | null
          load_disagreement: number | null
          session_goal_zone: Database["public"]["Enums"]["session_goal"] | null
          time_in_s1_s: number | null
          time_in_s2_s: number | null
          time_in_s3_s: number | null
          decoupling_pct: number | null
          decoupling_valid: boolean | null
          hr_source: string | null
          has_rr_intervals: boolean
          has_streams: boolean
          primary_provider: Database["public"]["Enums"]["provider"]
          provider_activity_id: string | null
          is_duplicate_of: string | null
          planned_workout_id: string | null
          created_at: string
        };
        Insert: {
          id?: string
          athlete_id: string
          sport: Database["public"]["Enums"]["sport"]
          sub_sport?: string | null
          start_time: string
          local_tz_offset_min: number
          duration_s: number
          moving_time_s?: number | null
          distance_m?: number | null
          elevation_gain_m?: number | null
          avg_hr?: number | null
          max_hr?: number | null
          avg_power_w?: number | null
          normalized_power_w?: number | null
          avg_speed_mps?: number | null
          avg_gap_speed_mps?: number | null
          avg_cadence?: number | null
          swim_avg_pace_s_per_100m?: number | null
          swim_stroke_count?: number | null
          temperature_c?: number | null
          humidity_pct?: number | null
          avg_altitude_m?: number | null
          external_load?: number | null
          internal_load?: number | null
          perceived_load?: number | null
          rpe?: number | null
          load_disagreement?: number | null
          session_goal_zone?: Database["public"]["Enums"]["session_goal"] | null
          time_in_s1_s?: number | null
          time_in_s2_s?: number | null
          time_in_s3_s?: number | null
          decoupling_pct?: number | null
          decoupling_valid?: boolean | null
          hr_source?: string | null
          has_rr_intervals?: boolean
          has_streams?: boolean
          primary_provider: Database["public"]["Enums"]["provider"]
          provider_activity_id?: string | null
          is_duplicate_of?: string | null
          planned_workout_id?: string | null
          created_at?: string
        };
        Update: {
          id?: string
          athlete_id?: string
          sport?: Database["public"]["Enums"]["sport"]
          sub_sport?: string | null
          start_time?: string
          local_tz_offset_min?: number
          duration_s?: number
          moving_time_s?: number | null
          distance_m?: number | null
          elevation_gain_m?: number | null
          avg_hr?: number | null
          max_hr?: number | null
          avg_power_w?: number | null
          normalized_power_w?: number | null
          avg_speed_mps?: number | null
          avg_gap_speed_mps?: number | null
          avg_cadence?: number | null
          swim_avg_pace_s_per_100m?: number | null
          swim_stroke_count?: number | null
          temperature_c?: number | null
          humidity_pct?: number | null
          avg_altitude_m?: number | null
          external_load?: number | null
          internal_load?: number | null
          perceived_load?: number | null
          rpe?: number | null
          load_disagreement?: number | null
          session_goal_zone?: Database["public"]["Enums"]["session_goal"] | null
          time_in_s1_s?: number | null
          time_in_s2_s?: number | null
          time_in_s3_s?: number | null
          decoupling_pct?: number | null
          decoupling_valid?: boolean | null
          hr_source?: string | null
          has_rr_intervals?: boolean
          has_streams?: boolean
          primary_provider?: Database["public"]["Enums"]["provider"]
          provider_activity_id?: string | null
          is_duplicate_of?: string | null
          planned_workout_id?: string | null
          created_at?: string
        };
        Relationships: [];
      };
      activity_laps: {
        Row: {
          id: string
          activity_id: string
          lap_index: number
          start_offset_s: number
          duration_s: number
          distance_m: number | null
          avg_hr: number | null
          avg_power_w: number | null
          avg_speed_mps: number | null
        };
        Insert: {
          id?: string
          activity_id: string
          lap_index: number
          start_offset_s: number
          duration_s: number
          distance_m?: number | null
          avg_hr?: number | null
          avg_power_w?: number | null
          avg_speed_mps?: number | null
        };
        Update: {
          id?: string
          activity_id?: string
          lap_index?: number
          start_offset_s?: number
          duration_s?: number
          distance_m?: number | null
          avg_hr?: number | null
          avg_power_w?: number | null
          avg_speed_mps?: number | null
        };
        Relationships: [];
      };
      activity_sources: {
        Row: {
          activity_id: string
          provider: Database["public"]["Enums"]["provider"]
          provider_activity_id: string
          ingested_at: string
        };
        Insert: {
          activity_id: string
          provider: Database["public"]["Enums"]["provider"]
          provider_activity_id: string
          ingested_at?: string
        };
        Update: {
          activity_id?: string
          provider?: Database["public"]["Enums"]["provider"]
          provider_activity_id?: string
          ingested_at?: string
        };
        Relationships: [];
      };
      activity_streams: {
        Row: {
          activity_id: string
          sample_rate_hz: number
          time_s: string | null
          hr: string | null
          rr_intervals: string | null
          power_w: string | null
          speed_mps: string | null
          altitude_m: string | null
          latlng: string | null
          cadence: string | null
          temperature_c: string | null
          compression: string
          created_at: string
        };
        Insert: {
          activity_id: string
          sample_rate_hz?: number
          time_s?: string | null
          hr?: string | null
          rr_intervals?: string | null
          power_w?: string | null
          speed_mps?: string | null
          altitude_m?: string | null
          latlng?: string | null
          cadence?: string | null
          temperature_c?: string | null
          compression?: string
          created_at?: string
        };
        Update: {
          activity_id?: string
          sample_rate_hz?: number
          time_s?: string | null
          hr?: string | null
          rr_intervals?: string | null
          power_w?: string | null
          speed_mps?: string | null
          altitude_m?: string | null
          latlng?: string | null
          cadence?: string | null
          temperature_c?: string | null
          compression?: string
          created_at?: string
        };
        Relationships: [];
      };
      athlete_anchors: {
        Row: {
          id: string
          athlete_id: string
          sport: Database["public"]["Enums"]["sport"] | null
          anchor_type: string
          value_numeric: number | null
          value_json: Json | null
          unit: string
          confidence: number
          provenance: Database["public"]["Enums"]["provenance"]
          sample_size: number | null
          source_activity_ids: string[] | null
          measured_at: string
          superseded_at: string | null
          created_at: string
        };
        Insert: {
          id?: string
          athlete_id: string
          sport?: Database["public"]["Enums"]["sport"] | null
          anchor_type: string
          value_numeric?: number | null
          value_json?: Json | null
          unit: string
          confidence: number
          provenance: Database["public"]["Enums"]["provenance"]
          sample_size?: number | null
          source_activity_ids?: string[] | null
          measured_at: string
          superseded_at?: string | null
          created_at?: string
        };
        Update: {
          id?: string
          athlete_id?: string
          sport?: Database["public"]["Enums"]["sport"] | null
          anchor_type?: string
          value_numeric?: number | null
          value_json?: Json | null
          unit?: string
          confidence?: number
          provenance?: Database["public"]["Enums"]["provenance"]
          sample_size?: number | null
          source_activity_ids?: string[] | null
          measured_at?: string
          superseded_at?: string | null
          created_at?: string
        };
        Relationships: [];
      };
      athlete_availability: {
        Row: {
          athlete_id: string
          weekly_hours_target: number
          weekly_hours_max: number
          day_minutes: Json
          swim_days: number[]
          long_ride_day: number | null
          long_run_day: number | null
          gym_access: boolean
          sauna_access: boolean
          notes: string | null
          updated_at: string
        };
        Insert: {
          athlete_id: string
          weekly_hours_target: number
          weekly_hours_max: number
          day_minutes: Json
          swim_days?: number[]
          long_ride_day?: number | null
          long_run_day?: number | null
          gym_access?: boolean
          sauna_access?: boolean
          notes?: string | null
          updated_at?: string
        };
        Update: {
          athlete_id?: string
          weekly_hours_target?: number
          weekly_hours_max?: number
          day_minutes?: Json
          swim_days?: number[]
          long_ride_day?: number | null
          long_run_day?: number | null
          gym_access?: boolean
          sauna_access?: boolean
          notes?: string | null
          updated_at?: string
        };
        Relationships: [];
      };
      athlete_model_current: {
        Row: {
          athlete_id: string
          model: Json
          combined_confidence: number
          computed_at: string
        };
        Insert: {
          athlete_id: string
          model: Json
          combined_confidence: number
          computed_at?: string
        };
        Update: {
          athlete_id?: string
          model?: Json
          combined_confidence?: number
          computed_at?: string
        };
        Relationships: [];
      };
      athlete_zones: {
        Row: {
          id: string
          athlete_id: string
          sport: Database["public"]["Enums"]["sport"]
          modality: string
          anchor_mode: string
          zones: Json
          valid_from: string
          valid_to: string | null
          created_at: string
        };
        Insert: {
          id?: string
          athlete_id: string
          sport: Database["public"]["Enums"]["sport"]
          modality: string
          anchor_mode: string
          zones: Json
          valid_from?: string
          valid_to?: string | null
          created_at?: string
        };
        Update: {
          id?: string
          athlete_id?: string
          sport?: Database["public"]["Enums"]["sport"]
          modality?: string
          anchor_mode?: string
          zones?: Json
          valid_from?: string
          valid_to?: string | null
          created_at?: string
        };
        Relationships: [];
      };
      coach_athlete_relationships: {
        Row: {
          id: string
          coach_id: string
          athlete_id: string
          status: string
          permissions: Json
          created_at: string
        };
        Insert: {
          id?: string
          coach_id: string
          athlete_id: string
          status?: string
          permissions?: Json
          created_at?: string
        };
        Update: {
          id?: string
          coach_id?: string
          athlete_id?: string
          status?: string
          permissions?: Json
          created_at?: string
        };
        Relationships: [];
      };
      daily_metrics: {
        Row: {
          athlete_id: string
          date: string
          ctl_total: number | null
          atl_total: number | null
          tsb_total: number | null
          ctl_by_sport: Json | null
          daily_load: number | null
          monotony: number | null
          strain: number | null
          hrv_rmssd: number | null
          hrv_rolling_7d: number | null
          hrv_baseline_60d: number | null
          hrv_baseline_sd: number | null
          resting_hr: number | null
          sleep_duration_min: number | null
          sleep_score: number | null
          body_mass_kg: number | null
          wellness_fatigue: number | null
          wellness_soreness: number | null
          wellness_stress: number | null
          wellness_mood: number | null
          illness_flag: boolean
          injury_flag: boolean
          injury_region: string | null
          readiness_score: number | null
          readiness_band: string | null
          readiness_inputs: Json | null
        };
        Insert: {
          athlete_id: string
          date: string
          ctl_total?: number | null
          atl_total?: number | null
          tsb_total?: number | null
          ctl_by_sport?: Json | null
          daily_load?: number | null
          monotony?: number | null
          strain?: number | null
          hrv_rmssd?: number | null
          hrv_rolling_7d?: number | null
          hrv_baseline_60d?: number | null
          hrv_baseline_sd?: number | null
          resting_hr?: number | null
          sleep_duration_min?: number | null
          sleep_score?: number | null
          body_mass_kg?: number | null
          wellness_fatigue?: number | null
          wellness_soreness?: number | null
          wellness_stress?: number | null
          wellness_mood?: number | null
          illness_flag?: boolean
          injury_flag?: boolean
          injury_region?: string | null
          readiness_score?: number | null
          readiness_band?: string | null
          readiness_inputs?: Json | null
        };
        Update: {
          athlete_id?: string
          date?: string
          ctl_total?: number | null
          atl_total?: number | null
          tsb_total?: number | null
          ctl_by_sport?: Json | null
          daily_load?: number | null
          monotony?: number | null
          strain?: number | null
          hrv_rmssd?: number | null
          hrv_rolling_7d?: number | null
          hrv_baseline_60d?: number | null
          hrv_baseline_sd?: number | null
          resting_hr?: number | null
          sleep_duration_min?: number | null
          sleep_score?: number | null
          body_mass_kg?: number | null
          wellness_fatigue?: number | null
          wellness_soreness?: number | null
          wellness_stress?: number | null
          wellness_mood?: number | null
          illness_flag?: boolean
          injury_flag?: boolean
          injury_region?: string | null
          readiness_score?: number | null
          readiness_band?: string | null
          readiness_inputs?: Json | null
        };
        Relationships: [];
      };
      field_tests: {
        Row: {
          id: string
          athlete_id: string
          workout_id: string | null
          sport: Database["public"]["Enums"]["sport"]
          protocol: string
          scheduled_date: string | null
          completed_at: string | null
          status: string
          raw_result: Json | null
          derived_anchor_ids: string[] | null
          quality_notes: string | null
        };
        Insert: {
          id?: string
          athlete_id: string
          workout_id?: string | null
          sport: Database["public"]["Enums"]["sport"]
          protocol: string
          scheduled_date?: string | null
          completed_at?: string | null
          status?: string
          raw_result?: Json | null
          derived_anchor_ids?: string[] | null
          quality_notes?: string | null
        };
        Update: {
          id?: string
          athlete_id?: string
          workout_id?: string | null
          sport?: Database["public"]["Enums"]["sport"]
          protocol?: string
          scheduled_date?: string | null
          completed_at?: string | null
          status?: string
          raw_result?: Json | null
          derived_anchor_ids?: string[] | null
          quality_notes?: string | null
        };
        Relationships: [];
      };
      integrations: {
        Row: {
          id: string
          athlete_id: string
          provider: Database["public"]["Enums"]["provider"]
          provider_user_id: string | null
          access_token_ref: string | null
          refresh_token_ref: string | null
          scopes: string[] | null
          connected_at: string
          last_sync_at: string | null
          last_sync_status: string | null
          consent_at: string
          revoked_at: string | null
        };
        Insert: {
          id?: string
          athlete_id: string
          provider: Database["public"]["Enums"]["provider"]
          provider_user_id?: string | null
          access_token_ref?: string | null
          refresh_token_ref?: string | null
          scopes?: string[] | null
          connected_at?: string
          last_sync_at?: string | null
          last_sync_status?: string | null
          consent_at: string
          revoked_at?: string | null
        };
        Update: {
          id?: string
          athlete_id?: string
          provider?: Database["public"]["Enums"]["provider"]
          provider_user_id?: string | null
          access_token_ref?: string | null
          refresh_token_ref?: string | null
          scopes?: string[] | null
          connected_at?: string
          last_sync_at?: string | null
          last_sync_status?: string | null
          consent_at?: string
          revoked_at?: string | null
        };
        Relationships: [];
      };
      mean_max_curves: {
        Row: {
          athlete_id: string
          sport: Database["public"]["Enums"]["sport"]
          metric: string
          window_start: string
          window_end: string
          curve: Json
          computed_at: string
        };
        Insert: {
          athlete_id: string
          sport: Database["public"]["Enums"]["sport"]
          metric: string
          window_start: string
          window_end: string
          curve: Json
          computed_at?: string
        };
        Update: {
          athlete_id?: string
          sport?: Database["public"]["Enums"]["sport"]
          metric?: string
          window_start?: string
          window_end?: string
          curve?: Json
          computed_at?: string
        };
        Relationships: [];
      };
      notifications: {
        Row: {
          id: number
          athlete_id: string
          kind: string
          title: string
          body: string
          deep_link: string | null
          plan_mutation_id: number | null
          read_at: string | null
          created_at: string
        };
        Insert: {
          id?: number
          athlete_id: string
          kind: string
          title: string
          body: string
          deep_link?: string | null
          plan_mutation_id?: number | null
          read_at?: string | null
          created_at?: string
        };
        Update: {
          id?: number
          athlete_id?: string
          kind?: string
          title?: string
          body?: string
          deep_link?: string | null
          plan_mutation_id?: number | null
          read_at?: string | null
          created_at?: string
        };
        Relationships: [];
      };
      plan_mutations: {
        Row: {
          id: number
          athlete_id: string
          plan_id: string
          occurred_at: string
          actor: string
          reason_code: string
          reason_text: string
          rule_id: string | null
          affected_workout_ids: string[] | null
          affected_week_ids: string[] | null
          before: Json | null
          after: Json | null
          engine_inputs: Json | null
        };
        Insert: {
          id?: number
          athlete_id: string
          plan_id: string
          occurred_at?: string
          actor: string
          reason_code: string
          reason_text: string
          rule_id?: string | null
          affected_workout_ids?: string[] | null
          affected_week_ids?: string[] | null
          before?: Json | null
          after?: Json | null
          engine_inputs?: Json | null
        };
        Update: {
          id?: number
          athlete_id?: string
          plan_id?: string
          occurred_at?: string
          actor?: string
          reason_code?: string
          reason_text?: string
          rule_id?: string | null
          affected_workout_ids?: string[] | null
          affected_week_ids?: string[] | null
          before?: Json | null
          after?: Json | null
          engine_inputs?: Json | null
        };
        Relationships: [];
      };
      plan_weeks: {
        Row: {
          id: string
          plan_id: string
          week_number: number
          week_start_date: string
          phase: Database["public"]["Enums"]["plan_phase"]
          is_recovery_week: boolean
          focus: string | null
          load_target: number
          hours_target: number
          distribution_target: Json
          distribution_actual: Json | null
          load_actual: number | null
          ramp_vs_prior_pct: number | null
          contains_race_id: string | null
        };
        Insert: {
          id?: string
          plan_id: string
          week_number: number
          week_start_date: string
          phase: Database["public"]["Enums"]["plan_phase"]
          is_recovery_week?: boolean
          focus?: string | null
          load_target: number
          hours_target: number
          distribution_target: Json
          distribution_actual?: Json | null
          load_actual?: number | null
          ramp_vs_prior_pct?: number | null
          contains_race_id?: string | null
        };
        Update: {
          id?: string
          plan_id?: string
          week_number?: number
          week_start_date?: string
          phase?: Database["public"]["Enums"]["plan_phase"]
          is_recovery_week?: boolean
          focus?: string | null
          load_target?: number
          hours_target?: number
          distribution_target?: Json
          distribution_actual?: Json | null
          load_actual?: number | null
          ramp_vs_prior_pct?: number | null
          contains_race_id?: string | null
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string
          display_name: string | null
          date_of_birth: string | null
          sex: string | null
          timezone: string
          week_start_day: number
          units: string
          training_age_years: number | null
          health_data_consent_at: string | null
          health_data_consent_version: string | null
          medical_disclaimer_ack_at: string | null
          created_at: string
          updated_at: string
        };
        Insert: {
          id: string
          display_name?: string | null
          date_of_birth?: string | null
          sex?: string | null
          timezone?: string
          week_start_day?: number
          units?: string
          training_age_years?: number | null
          health_data_consent_at?: string | null
          health_data_consent_version?: string | null
          medical_disclaimer_ack_at?: string | null
          created_at?: string
          updated_at?: string
        };
        Update: {
          id?: string
          display_name?: string | null
          date_of_birth?: string | null
          sex?: string | null
          timezone?: string
          week_start_day?: number
          units?: string
          training_age_years?: number | null
          health_data_consent_at?: string | null
          health_data_consent_version?: string | null
          medical_disclaimer_ack_at?: string | null
          created_at?: string
          updated_at?: string
        };
        Relationships: [];
      };
      races: {
        Row: {
          id: string
          athlete_id: string
          name: string
          race_date: string
          start_time_local: string | null
          priority: Database["public"]["Enums"]["race_priority"]
          event_type: string
          distance_swim_m: number | null
          distance_bike_m: number | null
          distance_run_m: number | null
          elevation_bike_m: number | null
          elevation_run_m: number | null
          location: string | null
          expected_temp_c: number | null
          expected_humidity_pct: number | null
          goal_time_s: number | null
          result_time_s: number | null
          result_notes: string | null
          created_at: string
        };
        Insert: {
          id?: string
          athlete_id: string
          name: string
          race_date: string
          start_time_local?: string | null
          priority: Database["public"]["Enums"]["race_priority"]
          event_type: string
          distance_swim_m?: number | null
          distance_bike_m?: number | null
          distance_run_m?: number | null
          elevation_bike_m?: number | null
          elevation_run_m?: number | null
          location?: string | null
          expected_temp_c?: number | null
          expected_humidity_pct?: number | null
          goal_time_s?: number | null
          result_time_s?: number | null
          result_notes?: string | null
          created_at?: string
        };
        Update: {
          id?: string
          athlete_id?: string
          name?: string
          race_date?: string
          start_time_local?: string | null
          priority?: Database["public"]["Enums"]["race_priority"]
          event_type?: string
          distance_swim_m?: number | null
          distance_bike_m?: number | null
          distance_run_m?: number | null
          elevation_bike_m?: number | null
          elevation_run_m?: number | null
          location?: string | null
          expected_temp_c?: number | null
          expected_humidity_pct?: number | null
          goal_time_s?: number | null
          result_time_s?: number | null
          result_notes?: string | null
          created_at?: string
        };
        Relationships: [];
      };
      sync_log: {
        Row: {
          id: number
          athlete_id: string
          provider: Database["public"]["Enums"]["provider"]
          job: string
          started_at: string
          finished_at: string | null
          activities_seen: number | null
          activities_new: number | null
          outcome: string | null
          error: string | null
        };
        Insert: {
          id?: number
          athlete_id: string
          provider: Database["public"]["Enums"]["provider"]
          job: string
          started_at?: string
          finished_at?: string | null
          activities_seen?: number | null
          activities_new?: number | null
          outcome?: string | null
          error?: string | null
        };
        Update: {
          id?: number
          athlete_id?: string
          provider?: Database["public"]["Enums"]["provider"]
          job?: string
          started_at?: string
          finished_at?: string | null
          activities_seen?: number | null
          activities_new?: number | null
          outcome?: string | null
          error?: string | null
        };
        Relationships: [];
      };
      training_plans: {
        Row: {
          id: string
          athlete_id: string
          primary_race_id: string | null
          name: string
          start_date: string
          end_date: string
          status: string
          model_snapshot: Json
          availability_snapshot: Json
          distribution_policy: Json
          engine_version: string
          created_at: string
          updated_at: string
        };
        Insert: {
          id?: string
          athlete_id: string
          primary_race_id?: string | null
          name: string
          start_date: string
          end_date: string
          status?: string
          model_snapshot: Json
          availability_snapshot: Json
          distribution_policy: Json
          engine_version: string
          created_at?: string
          updated_at?: string
        };
        Update: {
          id?: string
          athlete_id?: string
          primary_race_id?: string | null
          name?: string
          start_date?: string
          end_date?: string
          status?: string
          model_snapshot?: Json
          availability_snapshot?: Json
          distribution_policy?: Json
          engine_version?: string
          created_at?: string
          updated_at?: string
        };
        Relationships: [];
      };
      workouts: {
        Row: {
          id: string
          plan_week_id: string | null
          plan_id: string | null
          athlete_id: string
          scheduled_date: string
          sport: Database["public"]["Enums"]["sport"]
          template_id: string
          name: string
          description: string | null
          purpose: Database["public"]["Enums"]["session_purpose"]
          goal_zone: Database["public"]["Enums"]["session_goal"]
          is_key_session: boolean
          planned_duration_min: number
          planned_load: number
          structure: Json
          status: Database["public"]["Enums"]["workout_status"]
          completed_activity_id: string | null
          original_scheduled_date: string | null
          original_load: number | null
          pushed_to_device_at: string | null
          device_workout_id: string | null
          created_at: string
          updated_at: string
        };
        Insert: {
          id?: string
          plan_week_id?: string | null
          plan_id?: string | null
          athlete_id: string
          scheduled_date: string
          sport: Database["public"]["Enums"]["sport"]
          template_id: string
          name: string
          description?: string | null
          purpose: Database["public"]["Enums"]["session_purpose"]
          goal_zone: Database["public"]["Enums"]["session_goal"]
          is_key_session?: boolean
          planned_duration_min: number
          planned_load: number
          structure: Json
          status?: Database["public"]["Enums"]["workout_status"]
          completed_activity_id?: string | null
          original_scheduled_date?: string | null
          original_load?: number | null
          pushed_to_device_at?: string | null
          device_workout_id?: string | null
          created_at?: string
          updated_at?: string
        };
        Update: {
          id?: string
          plan_week_id?: string | null
          plan_id?: string | null
          athlete_id?: string
          scheduled_date?: string
          sport?: Database["public"]["Enums"]["sport"]
          template_id?: string
          name?: string
          description?: string | null
          purpose?: Database["public"]["Enums"]["session_purpose"]
          goal_zone?: Database["public"]["Enums"]["session_goal"]
          is_key_session?: boolean
          planned_duration_min?: number
          planned_load?: number
          structure?: Json
          status?: Database["public"]["Enums"]["workout_status"]
          completed_activity_id?: string | null
          original_scheduled_date?: string | null
          original_load?: number | null
          pushed_to_device_at?: string | null
          device_workout_id?: string | null
          created_at?: string
          updated_at?: string
        };
        Relationships: [];
      };
    };
    Views: { [_ in never]: never };
    Functions: { [_ in never]: never };
    Enums: {
      plan_phase: "base" | "build" | "peak" | "taper" | "recovery" | "race_week" | "transition";
      provenance: "lab_test" | "field_test" | "observed_max" | "dfa_a1_multi" | "cp_model_fit" | "athlete_reported" | "dfa_a1_single" | "passive_inference" | "population_formula";
      provider: "garmin" | "strava" | "apple_health" | "wahoo" | "polar" | "suunto" | "manual" | "fit_upload";
      race_priority: "A" | "B" | "C";
      session_goal: "S1" | "S2" | "S3";
      session_purpose: "aerobic_volume" | "threshold" | "vo2max" | "race_specific" | "durability" | "technique" | "recovery" | "brick" | "strength" | "heat_adaptation" | "field_test" | "rest";
      sport: "run" | "bike" | "swim" | "brick" | "strength" | "other";
      workout_status: "scheduled" | "completed" | "partial" | "skipped" | "moved" | "replaced";
    };
    CompositeTypes: { [_ in never]: never };
  };
}
